Some changes for more flexibility and prevention of the requirement to modiffy framework core files.
davidjconnelly/trongate-framework pull request #26
Opened 2020-12-30 19:09 UTC by MasterX1582

Made 'trongateToken' and 'trongatetoken' into a PHP variable for better flexibility on the choice of a token name and cookie name.

Added MODELDEBUG to config.php
$debug was previously only accessible from Model.php witch is part of the core framework. Its not advised that framework files are modified so this modification will benefit in the long run.

2020-12-31 14:18 UTC, delboy1978uk commented on config/config.php
> +define('MODELDEBUG', 'false');
make this an actual boolean and not a string, since you replace an actual boolean in `Model.php`

2020-12-31 14:22 UTC, delboy1978uk commented on engine/Model.php
> +        if (MYSQLDEBUG !== ''|| MYSQLDEBUG !== 'true'){
You can put this in a one liner something like this
`defined(MYSQLDEBUG) ?: define('MODELDEBUG', false);`

2020-12-31 14:24 UTC, delboy1978uk commented on modules/trongate_administrators/views/manage.php
> +        http.setRequestHeader('trongateToken', token)
if we replace the config, shouldn't this key change too?

2020-12-31 14:27 UTC, delboy1978uk commented on modules/trongate_administrators/views/manage.php
> +        http.setRequestHeader('trongateToken', token)
same qusetion here

2020-12-31 14:30 UTC, delboy1978uk requested changes
looks ok but still wondering about the hard code strings in the javascript

2020-12-31 14:30 UTC, delboy1978uk commented on modules/trongate_administrators/views/manage.php
> +        http.setRequestHeader('trongateToken', token)
same question here

2020-12-31 14:30 UTC, delboy1978uk commented on modules/trongate_administrators/views/manage.php
> +        http.setRequestHeader('trongateToken', token)
same question here

2021-01-13 08:41 UTC, davidjconnelly commented
Hi.  I have taken your 'debug' request on board but instead of having the thing being declared inside config, I have it so that you can optionally declare it inside database.php.  The name of the constant is CONFIG.  So, even though it's not quite as you had it down, the model tweak has been taken on board.  I have not yet uploaded but you'll see it soon.  Cheers!

2021-01-13 08:41 UTC, closed without merging